apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-eks-loki-241025-migration-ap-northeast-2d
  labels:
    name: pvc-eks-loki-241025-migration-ap-northeast-2d       
spec:
  capacity:
    storage: 30Gi  # 실제 EBS와 동일한 값으로
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  
  # gp2: 헬름차트의 신규 PVC설정에서도 동일한 storageClass를 써주면, available상태인 pv를 자동으로 찾아 연결한다(동적프로비저닝)
  # "": 정적 프로비저닝. PVC도 별도 메니페스트로 직접생성 필요
  storageClassName: gp2 # ""

  awsElasticBlockStore: 
    volumeID: vol-xxxxxxxxxxxxx   # 수동생성(복제)한 EBS 볼륨아이디
    fsType: ext4

# 헬름차트로 배포된 Loki의 EBS PV를 마이그레이션 하는 방법
# 1. 기존 EBS의 스냅샷을 만들어 신규 EBS 복제본 생성
# 2. 매니페스트로 PV생성하여 복제된 EBS와 연동
# 3. storageClassName을 PV와 동일하게 지정 후, 신규 헬름차트로 배포(PVC가 자동생성되면서 미리 생성된 PV와 연동됨)
#   => helm upgrade로는 PVC 수정이 불가하므로, 기존 릴리즈,PVC 삭제후 신규배포하는 방식으로 진행해야 함 
