# kubectl apply -f loki-stroage-class.yaml
# /data 와 같이 별도 마운트된 경로에 저장하고 싶을 시 신규 storageClass 생성이 필요
# 이후 pv 설정의 storageClassName섹션에서 이 storageClass 이름을 등록

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-loki
  # annotations:
    # storageclass.kubernetes.io/is-default-class: "true"
# 다양한 provisioner들이 있고, 보통은 K8s 배포판에 따라 정해지는 듯
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

# provisioner에 따라 syntax 다름
parameters: 
  nodePath: /data

# https://github.com/rancher/local-path-provisioner#local-path-provisioner
# https://artifacthub.io/packages/helm/ebrianne/local-path-provisioner


# storageclass 추가설정만으로 다른 PV에 실행하는 것은 불가능
# provisioner에서 node가 사용하는 storage 기본경로에 새로운 경로를 추가해야한다.
# 기존 배포판에 포함된 provisioner를 비활성화하고 새로 커스텀하여 배포해야 함

# 간단하게 마운트 하는 방법은 없나??? 뭔가 좀 이상한데
