apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv   # 이름 고정
  labels:
    name: loki-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
  # claimRef:
  #   name: loki-pv-claim
  #   namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  # pvc가 조건에 맞는 pv를 찾는게 아니라, 특정 pv를 참조하도록 설정
  selector:
    matchLabels:
      name: loki-pv
  storageClassName: ""